### ISSUE TITLE
报错报错！！！

### ISSUE THREAD

**Issue by songguowei** [Autokaka/refined_video_player#1]
Compiler message:
../lib/src/video_player.dart:448:17: Error: No named parameter with the name 'pressedElevation'.
                pressedElevation: 10,
                ^^^^^^^^^^^^^^^^
/E:/Program%20Files/Git/flutter/packages/flutter/lib/src/material/slider_theme.dart:2215:9: Context: Found this candidate, but the arguments don't match.
  const RoundSliderThumbShape({
        ^^^^^^^^^^^^^^^^^^^^^

**Comment by Autokaka** [comment]
可以给我看看你的flutter doctor -v嘛？
可能是我这边使用了flutter的master分支的缘故.

**Comment by Autokaka** [comment]
我已经移除了可能涉及到flutter master分支新特性的代码. 请尝试使用flutter_master_fix分支的版本.

**Comment by Autokaka** [comment]
这个issue我关掉了, 如果还还有问题的话你可以重新打开.
