### ISSUE TITLE
m3u8不能播放吗？报错了

### ISSUE THREAD

**Issue by songguowei** [Autokaka/refined_video_player#2]
https://youku.cdn11-okzy.com/20200525/16893_c8f179a6/index.m3u8
https://cdn.jsdelivr.net/gh/myxuwei123/lucky/movie/jingjuegucheng_01.m3u8

V/AudioManager(27477): querySoundEffectsEnabled...
I/ExoPlayerImpl(27477): Init 94b901f [ExoPlayerLib/2.11.7] [HWHMA, HMA-AL00, HUAWEI, 29]
I/DecorView[](27477):  old windowMode:0 new windoMode:1
D/OpenGLRenderer(27477): disableOutlineDraw is true
I/HiTouch_HiTouchSensor(27477): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(27477): onAttached, package=cn.dshitpie.refined_video_player_example, windowType=2030, mHiTouchRestricted=true
D/mali_winsys(27477): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
V/AudioManager(27477): getStreamVolume streamType: 3 volume: 6
E/ExoPlayerImplInternal(27477): Source error
E/ExoPlayerImplInternal(27477):   com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
E/ExoPlayerImplInternal(27477):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1096)
E/ExoPlayerImplInternal(27477):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:975)
E/ExoPlayerImplInternal(27477):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(27477):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(27477):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(27477):       at java.lang.Thread.run(Thread.java:929)
W/System  (27477): A resource failed to call release.

**Comment by Autokaka** [comment]
不能播放, 这几天看看要如何支持

**Comment by Autokaka** [comment]
已经适配好了, 试一试最新的master和flutter_stable_fit分支的提交看看. 如果没问题了的话, 三天后我将关闭此issue
