### ISSUE TITLE
没有pub的包吗，github的包死活下载不下来

### ISSUE THREAD

**Issue by songguowei** [Autokaka/refined_video_player#3]

**Comment by Autokaka** [comment]
因为iOS那边的版本没有做好, 只支持一个平台是在太不好意思上仓库了, 所以暂时没有上传pub的打算. 我去gitee开个镜像仓库, 稍等.

**Comment by Autokaka** [comment]
镜像做好了, gitee, 用这个试试https://gitee.com/Autokaka/refined_video_player
