### ISSUE TITLE
切换播放地址有点问题！！！

### ISSUE THREAD

**Issue by songguowei** [Autokaka/refined_video_player#5]
切换地址  缓存UI一直显示，进度条和时间没有获取到

但是视频已经播放了

@override
  void initState() {
    super.initState();
    controller = RVPController(
      widget.dataSource,
    );
  }

@override
  void didUpdateWidget(VideoPlayer oldWidget) {
    if (widget.dataSource == controller.url) {
      super.didUpdateWidget(oldWidget);
    } else {
      Future.wait([
        controller.setMediaSource(widget.dataSource),
      ]).then(
        (value) => super.didUpdateWidget(oldWidget),
      );
    }
  }

@override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

@override
  Widget build(BuildContext context) {
    playerInstance = RefinedVideoPlayer(
      controller: controller,
      topAreaBuilder: buildTopArea,
      onGestureTap: () => setState(
        () => showTopArea = !showTopArea,
      ),
    );
    return SafeArea(child: playerInstance);
  }

**Comment by Autokaka** [comment]
能发一下你那边控制台的log吗？我需要排除视频源出错的可能性

**Comment by songguowei** [comment]
> 能发一下你那边控制台的log吗？我需要排除视频源出错的可能性

就是一开始没有播放地址，然后切换地址就会出现这个

**Comment by Autokaka** [comment]
你这么一说我大概知道是怎么回事了, 我Native和Flutter那边全都没有处理链接为空的逻辑.

正在改代码. 如果你急着用的话, 在RefinedVideoPlayer外层套一个Offstage(offstage: url == null, child: RefinedVideoPlayer...)试一试先.

**Comment by Autokaka** [comment]
已经修复了. 我在Native那边做了url有效性检测, 新增了播放器报错回调onError. 三天后没出现其他问题的话, 我会关闭这个Issue.
