### ISSUE TITLE
进入全屏和退出全屏都会卡

### ISSUE THREAD

**Issue by songguowei** [Autokaka/refined_video_player#6]
尤其是退全屏会黑屏一下！

**Comment by Autokaka** [comment]
我用Hero做的全屏功能. 刚开始全屏切换的时候, Native那边有时候会引用旧的已经销毁的Surface, 然后Flutter这边会被断言中断. 虽然忽略这个断言并没有出现什么奇怪的问题, 内存也没有溢出. 后来我直接在重新getView的时候设置的全屏全屏切换, 解决了这个问题, 但是切换的时候确实会存在短暂黑屏. 我这边日常使用的时候黑屏时间不是很长, 大概500ms, 不怎么影响使用的样子, 后来就一直采用这个不怎么优雅地办法了.

你使用的时候黑屏时间很长吗? 问题比较严重的话我再想想其他解决的办法.

**Comment by songguowei** [comment]
> 我用Hero做的全屏功能. 刚开始全屏切换的时候, Native那边有时候会引用旧的已经销毁的Surface, 然后Flutter这边会被断言中断. 虽然忽略这个断言并没有出现什么奇怪的问题, 内存也没有溢出. 后来我直接在重新getView的时候设置的全屏全屏切换, 解决了这个问题, 但是切换的时候确实会存在短暂黑屏. 我这边日常使用的时候黑屏时间不是很长, 大概500ms, 不怎么影响使用的样子, 后来就一直采用这个不怎么优雅地办法了.
> 
> 你使用的时候黑屏时间很长吗? 问题比较严重的话我再想想其他解决的办法.

我这边卡那么 一到两秒，切换的时候播放器会占半个屏然后一到两秒恢复

**Comment by Autokaka** [comment]
看起来问题还是很大...这个问题需要花点时间解决，得等等

**Comment by Autokaka** [comment]
> 我这边卡那么 一到两秒，切换的时候播放器会占半个屏然后一到两秒恢复

这个问题最新的版本上已经修复了, 我自己测试的时候感觉效果很理想. 你试试看效果怎样. 
如果没有问题的话, 我将会在3天后关闭此issue.
