### ISSUE TITLE
切换视频后进度还是上一个视频的进度

### ISSUE THREAD

**Issue by songguowei** [Autokaka/refined_video_player#7]
切换视频后进度还是上一个视频的进度，但是这个视频是从开始播放的

**Comment by Autokaka** [comment]
大概知道是什么问题了...这几天有时间改一下

**Comment by Autokaka** [comment]
> 切换视频后进度还是上一个视频的进度，但是这个视频是从开始播放的

我这边自己测试了一下, 没有出现你描述的问题... 
仔细思考了一下, 我有以下几个思路:
1. 上次提交的时候, 我忘记了立即同步gitee的源码, 延后了几天才做了同步, 你可能在没有使用最新源码的情况下使用了旧的插件. 
   直接使用git仓库需要在每次refined_video_player有新提交的时候重新在pubspec.yaml里面get packages, 具体做法如下:
      1) 在pubspec.yaml里面注释掉refined_video_player那一行
      2) terminal 里面, 在你的项目根目录输入flutter pub get
      3) 去掉pubspec.yaml的注释
      4) terminal 里面, 再次输入flutter pub get
2. 如果你确认你已经使用仓库最新的源码, 问题仍然出现, 在你愿意的情况下, 能否给我提供一个问题出现时的测试代码.
   我这边自己测试的时候, 模拟了你的描述, 但没有办法复现你所说的问题, 可能得麻烦你给我提供一个测试代码.
   代码留在这个issue里面, 或者你另开仓库, 把仓库地址给我, 都可以. 我定位到问题后会第一时间给你进一步的答复.
