### ISSUE TITLE
切到后台不暂停吗？

### ISSUE THREAD

**Issue by songguowei** [Autokaka/refined_video_player#9]
切到后台暂停，切回来播放   不应该是这样吗

**Comment by Autokaka** [comment]
噢噢忘做了, 我补一下...

**Comment by Autokaka** [comment]
已经做好了. 我在RefinedVideoPlayer内添加了一个选项: autoManageAppLifecycle. 这个值默认为true. 当这个值为true时, 播放器会自动处理你在本Issue内提出的需求.

如果你有更加复杂的自定义需求, 你只需要把autoManageAppLifecycle设定为false, 然后在你的自定义播放器组件内使用mixin. 实现方式和RefinedVideoPlayer内部的实现原理是一样的:

![image](https://user-images.githubusercontent.com/20894949/91864188-821cbd00-eca2-11ea-90c5-bf49298bcb5a.png)

![image](https://user-images.githubusercontent.com/20894949/91864284-9eb8f500-eca2-11ea-8ea3-eee564e7b63c.png)

顺便一提, flutter_stable_fit分支改为了flutter-stable, 如果你在使用flutter stable分支的版本请切换到那个分支上去, 原flutter_stable_fit已经被我删掉了.

如果后续没有任何问题, 我将会在3天后关闭此Issue
